### ISSUE TITLE
Authentication fails

### ISSUE THREAD

**Issue by pReya** [Fensterbank/easyverein#1]
Hey @Fensterbank, thanks for the library. Unfortunately it seems, that easyVerein changed their auth method. Documentation still says it's a bearer token, like it used to be in the past – but it doesn't work anymore. Whenever I send a request with a valid Bearer token, I get this error (e.g. the example code from your readme that calls `getOrganization()`):

```
{ detail: 'Ungültiger token header. Keine Zugangsdaten angegeben.' }
```

Any idea where the new auth system is described or how I can fix this?

**Comment by Fensterbank** [comment]
Hi @pReya,
It is not a real "Bearer Token", since there is no Bearer term in the header. :)

So the HTTP request header is something like `Authorization: Token 9af2a…60a22`. When you use Insomnia or any other HTTP debugging tool, you can't use the classic auth options, instead you have to add it to the Headers.

I tested the library and the API methods itself using my auth token and it still works for me, also all my apps are still running.

When I don't send the auth token, I get `403 { "detail": "Anmeldedaten fehlen." }`, when I send a wrong auth token, I get `403 { "detail": "Ungültiges Token" }`. I tested with API version 1.2 and 1.3.
It's interesting that I could not reproduce the message you got `Ungültiger token header. Keine Zugangsdaten angegeben.`, so I don't know what you did, but something is different here.

I would propose you try to debug the API directly with a tool like Insomnia. Also you can try to contact the support. Since you get an error message I could not reproduce, it is possible this has something directly to do with your account, so maybe the API access is disabled or something else weird is the case here.

**Disclaimer:** I'm going in holidays and won't have access to my development machine starting today until 12th August, so I won't be able to debug more.

**Comment by pReya** [comment]
Hey @Fensterbank thanks for the quick reply. Indeed, it was an error on my side. I used the defaul Authorization header in my API Client (Postman), which creates a header in the shape of `Authorization: Bearer abc123`, but I needed `Authorization: Token abc123`. Thanks!

Your library failed for me, because the given token did not have the right scope for the operation I was trying to perform. So it was unrelated to the auth header.
